config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get 'about', to: "pages#about"

  resources :articles

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, except: [:new]
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories

	validates :title, presence: true, length: {minimum: 6, maximum: 100}
	validates :description, presence: true, length: { minimum: 10, maximum: 300}
	validates :user_id, presence: true
end	

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :category
	belongs_to :article
end	

app/models/category.rb
class Category < ActiveRecord::Base
	
	has_many :article_categories
	has_many :articles, through: :article_categories

	validates :name, presence: true, length: {minimum: 3, maximum: 25}
	validates_uniqueness_of :name

end	

app/models/user.rb
class User < ActiveRecord::Base

	has_many :articles, dependent: :destroy

	before_save { self.email = email.downcase }

	validates :username, presence: true, uniqueness: { case_sensitive: false}, length: {minimum: 3, maximum: 25}
	validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 105}
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

	has_secure_password
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # def hello
  # 	render html: "hello world!"
  # end

  helper_method :current_user, :logged_in?  #whatever we write in application controller, it avialable for all controller but it is not availbale for views so we make them availbale by adding thios helper_method in our application controller

  def current_user
  	@current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user # !! is used to convert in boolean
  end

  def require_user
  	if !logged_in? #if not logged_in? 
  		flash[:danger] = "You need to login to continue"
  		redirect_to root_path
  	end	
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:show, :update, :destroy, :edit]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def show
	end

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Article was created successfully."
			# render plain: @article.inspect
			redirect_to @article
		else
			render 'new'
		end	
	end

	def edit
	end

	def update
		@article.update_attributes(article_params)
		if @article.save
			flash[:success] = "Article was updated successfully."
			redirect_to @article
		else
			render 'edit'	
		end
	end	

	def destroy
		if @article.destroy
			flash[:danger] = "Article was deleted successfully."
			redirect_to articles_path
		else
		end	
	end	

	private

	def article_params
		params.require(:article).permit(:title, :description, category_ids: []) #[] defines it is gonna come in array as we have many to many association with category
	end

	def set_article
		@article = Article.find(params[:id])
	end

	def require_same_user
		if current_user != @article.user and !current_user.admin?
			flash[:danger] = "You can only edit or delete your own articles"
			redirect_to root_path
		end	
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_admin, only: [:new, :create]

	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.create(category_params)
		if @category.save
			flash[:success] = "Category was created successfully"		
		    redirect_to categories_path
		else
			render 'new'
		end    
	end	

	def show
		@category = Category.find(params[:id])
		@category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		@category.update_attributes(category_params)
		if @category.save
			flash[:notice] = "Category name was updated successfully."
			redirect_to category_path(@category)
		else
			render 'edit'
		end	
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || (logged_in? && !current_user.admin?)
			flash[:danger] = "Only admin can perform this action"
			redirect_to categories_path 
		end	
	end

end	

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?	
	end

	def about
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			flash[:success] = "You have successfully logged in."
			#information is being stored in session hash 
			session[:user_id] = user.id  #storing user_id in session hash so browser cookies are going to handle this wheater the user is login or not
			redirect_to user_path(user)
		else
			flash.now[:danger] = "There is something wrong with your login credential." #because there is no model for this there is no validation message, flash consist every new http rerquest and show the msg on the next page as we are not redirecting anywhere so we use flash.now it doesn't consider any http request.
			render 'new'
		end	
	end

	def destroy
		session[:user_id] = nil #setting user_id to nil
		flash[:success] = "You have successfully logged out."
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new	
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id #we also logged in user by saving user_id to session
			flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end	
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def edit
	end

	def update
		@user.update_attributes(user_params)
		if @user.save
			flash[:success] = "Profile updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end		
	end

	def destroy
		@user.destroy
		flash[:danger] = "User and all articles created by user have been deleted"
		redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user and !current_user.admin?
			flash[:danger] = "You can only edit your own profile"
			redirect_to root_path
		end	
	end

	def require_admin
		if logged_in? && !current_user.admin?
			flash[:danger] = "Only Admin users can perform  that action"
			redirect_to root_path
		end	
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper

	#whatever methods we written in this file it availble to all the views
	
	def gravator_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase) #It will fetch Image for selected Email
		size = options[:size] #It takes  the size of the image
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}" #Takes image url
		image_tag(gravatar_url, alt: user.username, class: "img-circle") #gives the image in circle format for selected user
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
					<%= link_to article.title, article_path(article) %>
				</div>
				<div class="article-body">
				    <%= truncate(article.description, length: 100) %>
				    <div class="article-meta-details">
					    <small>
					    	Created By: <%= article.user.username if article.user %> , <%= time_ago_in_words(article.created_at)%> ago, Last updated: <%= time_ago_in_words(article.updated_at)%> ago
					    </small>
					</div>    
				</div>
				<% if article.categories.any? %>
					<p>Categories: <%= render article.categories %></p>  <%#render and variable works as same as each method, it render the partial _category.html.erb%>
				<% end %>
				<div class="article-actions">
					<% if logged_in? && (current_user == article.user || current_user.admin? )%>
						<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
						<%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"},class: "btn btn-xs btn-danger" %>
					<% end %>	
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>

<div class="row">
<div class="col-xs-12">
<%= form_for(@article , :html => { class: "form-horizontal", role: "form" }) do |f| %>
    <div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :title%><br>
		</div>
		<div class="col-sm-8">
			<%= f.text_field :title, class: "form-control", placeholder: "Title"%>
		</div>
	</div>
	<div class="form-group">		
		<div class="control-label col-sm-2">
			<%= f.label :description%>
		</div>
		<div class="col-sm-8">	
			<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
		</div>
	</div>	
	<div class="form-group">
		<div class="row">
			<div class="col-sm-offset-2 col-sm-8">
				<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
					<% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
				<% end %>
			</div>
		</div>	
	</div>
	<div class="form-group">		
		<div class="col-sm-offset-2 col-sm-10">
		   <%= f.submit class: "btn btn-primary btn-lg"%>
		</div>
	</div>	  
	</p>
	</div>
<%end%>
<div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to "Cancel request and return to Articles listing", articles_path %> ]
</div>
</div> 

app/views/articles/edit.html.erb
<h2 class="center">Update an Article</h2>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<%= render 'article', obj: @articles %>

<center><%= will_paginate @article%></center>

app/views/articles/new.html.erb
<h2 class="center">Create an Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<% if @article.user %>
		<ul class="listing">
			<div class="row center">
				<div class="col-md-4 col-md-offset-4">
					Created By:
					<li><%= link_to gravator_for(@article.user), user_path(@article.user) %></li>
					<li class="article-title">
						<%= link_to @article.user.username, user_path(@article.user) %>
					</li>
					<li><small><%= pluralize(@article.user.articles.count, "Articles") if @article.user.articles %></small></li>
				</div>
			</div>
		</ul>
	<% end %>		
	<h4 class="center description"><strong>Description: </strong></h4>
	<% if @article.categories.any? %>
		<p>Categories: <%= render @article.categories %></p>  <%#render and variable works as same as each method, it render the partial _category.html.erb%>
	<% end %>
	<br>
	 <%= simple_format(@article.description) %>
	<div class="article-actions"> 
		<% if logged_in? && (current_user == @article.user || current_user.admin?)%>
			<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
			<%= link_to 'Delete this article', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
		<% end %>	
		<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %> 
    </div>
</div> 
   

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category%>

<%= form_for(@category , :html => { class: "form-horizontal", role: "form" }) do |f| %>
    <div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :name%><br>
		</div>
		<div class="col-sm-8">
			<%= f.text_field :name, class: "form-control", placeholder: "Category Name"%>
		</div>
	</div>	
	<div class="form-group">		
		<div class="col-sm-offset-2 col-sm-10">
		   <%= f.submit class: "btn btn-primary btn-lg"%>
		</div>
	</div>	  
	</p>
	</div>
<%end%>

app/views/categories/edit.html.erb
<h2 align="center">Update Category</h2>

<%= render 'form'%>

app/views/categories/index.html.erb
<h1 align="center">Listing all categories</h1>
<div align="center">
<% @categories.each do |category| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
					<%= link_to category.name, category_path(category) %>
				</div>
				<small><%= pluralize(category.articles.count, "Articles" )%></small>
			</div>
		</div>
	</div>
<% end %>
<%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h2 align="center">Create New Category</h2>

<%= render 'form'%>

app/views/categories/show.html.erb
<h2 align="center"><%= "Category: " + @category.name %></h2>
<div align="center">
		<%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-xs btn-info" if logged_in? && current_user.admin? %>
</div>
<div style="padding-bottom: 15px;"></div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
	<%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>© Copyright 2018 Blog App - All Rights Reserved</small>
	<nav>
		<ul>
		    <li><%= link_to "About", about_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%="#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">×</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <!-- <a class="navbar-brand" id="logo" href="#">ALPHA BLOG</a> -->
      <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <ul class="nav navbar-nav">
      <li ><%= link_to "Articles" , articles_path %></li>
      <% if logged_in? %>
        <li><%= link_to "New Article", new_article_path %></li>
      <% end %>  
      <li><%= link_to "Users", users_path %></li>
      <li class="dropdown">
        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#" aria-expanded="false">
          Categories &nbsp; <i class="caret"></i>
        </a>
        <ul class="dropdown-menu dropdown-settings">
          <li><%= link_to "All Categories", categories_path %></li>
          <% Category.all.each do |category| %>
            <li><%= link_to "#{category.name}", category_path(category) %></li>
          <% end %>  
          <% if logged_in? and current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Create New Category", new_category_path %></li>
          <% end %>
        </ul> 
      </li>   
    </ul>

    <form class="navbar-form navbar-left" action="/action_page.php">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <li class="dropdown">
          <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %> &nbsp; <i class="caret"></i>
          </a>
          <ul class="dropdown-menu dropdown-settings">
            <li>
              <%= link_to user_path(current_user) do %>
              <i class="fa fa-user"></i> &nbsp; Profile
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_path(current_user) do %>
              <i class="fa fa-pencil"></i> &nbsp; Edit Profile
              <% end %>
            </li>
            <!-- <li>
              <%#= link_to edit_user_registration_path do %>
              <i class="fa fa-unlock"></i> &nbsp; Change Password
              <%# end %>
            </li> -->
            <li class="divider"></li>
            <li>
              <%= link_to logout_path, method: :delete do %>
              <i class="fa fa-sign-out"></i> Log out
              <% end %>
            </li>
 
          </ul>
        </li> 
      <% else %>  
        <li ><%= link_to "Log In" , login_path %></li>
        <li ><%= link_to "Sign Up" , signup_path %></li>
      <% end %>  
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>AlphaApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
  	<%= render 'layouts/messages'%>
    <%= yield %>
    <%= render 'layouts/footer' %>  
    <%#= debug(params)  if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to "Home Page", root_path%> | 
<%= link_to "Create a new article", new_article_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <h1>Alpha Blog</h1>      
	<%= link_to "Sign Up Now", signup_path , class: "btn btn-primary btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-5 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class='panel-title'>
						<% pluralize(obj.errors.count, "error")%>
						Prohabited this article from being saved:
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
						    <li><%= msg %></li>
						  <% end%> 
					    </ul> 
					</div>
				</div>
			</div>    
	  </div>
	</div>  
<% end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>

<div class="row">
<div class="col-xs-12">
<%= form_for(@user , :html => { class: "form-horizontal", role: "form" }) do |f| %>
    <div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :username%><br>
		</div>
		<div class="col-sm-8">
			<%= f.text_field :username, class: "form-control", placeholder: "enter Username"%>
		</div>
	</div>
    <div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :email%><br>
		</div>
		<div class="col-sm-8">
			<%= f.email_field :email, class: "form-control", placeholder: "Enter Email"%>
		</div>
	</div>
	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :password%><br>
		</div>
		<div class="col-sm-8">
			<%= f.password_field :password, class: "form-control", placeholder: "Enter Password"%>
		</div>
	</div>
	<div class="form-group">		
		<div class="col-sm-offset-2 col-sm-10">
		   <%= f.submit(@user.new_record? ? "Sign Up" : "Updated Account", class: "btn btn-primary btn-lg")%>
		</div>
	</div>	  
	</p>
	</div>
<%end%>
<div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to "Cancel request and return to Articles listing", articles_path %> ]
</div>
</div> 

app/views/users/edit.html.erb
<h2 align="center">Edit Your Account</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h2 align="center">List Of Alpha Blogger</h2>
<div align="center">
<% @users.each do |user| %>
	<ul class="listing">
		<div class="row">
			<div class="well col-md-4 col-md-offset-4">
				<li><%= link_to gravator_for(user), user_path(user) %></li>
				<li class="article-title">
					<%= link_to user.username, user_path(user) %>
				</li>
				<li><small><%= pluralize(user.articles.count, "Articles") if user.articles %></small></li>
				<% if logged_in? && current_user.admin? %>
					<%= link_to "Delete this User", user_path(user), method: :delete, data: {confirm: "Are you sure?"} ,class: "btn btn-xs btn-danger"%>
				<% end %>
			</div>
		</div>
	</ul>	
<% end %>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h2 align="center">Signup for Alpha Blog</h2>

<%= render 'form'%>

app/views/users/show.html.erb
<h2 align="center">Welcome To <%= @user.username %>'s Profile</h2>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravator_for(@user, size: 150) %>
	</div>
</div>
<h4 align="center"><%= @user.username%>'s Articles</h4>
<%= render 'articles/article', obj: @user.articles %>
<div align="center">	
	<%= will_paginate @user_articles %>
</div>	